# Generated by Django 4.2.27 on 2026-02-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mini',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='')),
                ('product_name', models.CharField(max_length=120)),
                ('product_price', models.IntegerField(max_length=10)),
                ('product_dprice', models.IntegerField(max_length=10)),
            ],
        ),
    ]
