# Generated by Django 4.2.27 on 2026-02-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_mini_product_dprice_alter_mini_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newarrivals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newproduct_image', models.ImageField(upload_to='newarrivals')),
                ('newproduct_name', models.CharField(max_length=120)),
                ('newproduct_price', models.IntegerField()),
                ('newproduct_dprice', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='mini',
            name='product_image',
            field=models.ImageField(upload_to='miniature'),
        ),
    ]
