# Generated by Django 4.2.27 on 2026-02-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_newarrivals_alter_mini_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bestsellers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bestproduct_image', models.ImageField(upload_to='bestsellers')),
                ('bestproduct_name', models.CharField(max_length=120)),
                ('bestproduct_price', models.IntegerField()),
                ('bestproduct_dprice', models.IntegerField()),
            ],
        ),
    ]
