# Generated by Django 4.2.27 on 2026-02-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_bestsellers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coproduct_image', models.ImageField(upload_to='Community')),
                ('coproduct_video', models.FileField(upload_to='Community')),
                ('coproduct_name', models.CharField(max_length=120)),
                ('coproduct_price', models.IntegerField()),
            ],
        ),
    ]
