# Generated by Django 4.2.27 on 2026-02-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_community'),
    ]

    operations = [
        migrations.CreateModel(
            name='minicombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miniproduct_image', models.ImageField(upload_to='miniature')),
                ('miniproduct_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='community',
            name='coproduct_image',
            field=models.ImageField(upload_to='Comunity'),
        ),
    ]
