# Generated by Django 4.2.27 on 2026-02-22 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_minicombo_alter_community_coproduct_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='minicombo',
        ),
    ]
