# Generated by Django 4.2.27 on 2026-02-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_delete_minicombo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mini',
            name='product_sex',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
    ]
