# Generated by Django 4.2.27 on 2026-02-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_category_product_delete_bestsellers_delete_community_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dprice',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
