# Generated by Django 4.2.27 on 2026-02-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_product_dprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='genter',
            field=models.CharField(blank=True, max_length=130, null=True),
        ),
    ]
