# Generated by Django 4.2.27 on 2026-02-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_product_video_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Comunity')),
                ('video', models.FileField(upload_to='Community')),
                ('name', models.CharField(max_length=120)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='video',
        ),
    ]
