# Generated by Django 4.2.27 on 2026-02-26 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_community_remove_product_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ML',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
