# Generated by Django 4.2.27 on 2026-04-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_rename_cartproducts_cartitem_products_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Community',
        ),
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='products'),
        ),
    ]
