# Generated by Django 4.2.27 on 2026-04-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_delete_community_product_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='videos',
            field=models.FileField(blank=True, null=True, upload_to='products'),
        ),
    ]
