# Generated by Django 4.2.27 on 2026-04-07 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_product_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='videos',
        ),
    ]
