# Generated by Django 4.2.27 on 2026-04-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='error',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
