# Generated by Django 4.2.27 on 2026-04-11 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_userprofile_error'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='error',
        ),
    ]
