# Generated by Django 4.2.27 on 2026-04-15 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_order_address_order_created_at_order_delivery_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='products',
            new_name='product',
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
